version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    container_name: postgresql_container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_postgres: todolist
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres-network
    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "2345:2345"
    depends_on:
      - postgres
    networks:
      - postgres-network

  nginx:
    build: ./scripts/dockerfiles/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    command: ["nginx", "-g", "daemon off;"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://web:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      
volumes:
  postgres_data:
  static_volume:

networks:
  postgres-network:
    driver: bridge

