version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - db-network

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.prod.pg
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - db-network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
      
volumes:
  postgres_data:
  static_volume:

networks:
  db-network:
    driver: bridge

