services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - application

  nginx:
    build: ./scripts/dockerfiles/nginx
    volumes:
      - static_volume_dev:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    command: ["nginx", "-g", "daemon off;"]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://web:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  static_volume_dev:

networks:
  application:
    driver: bridge